In [1]:
#data of the home page first part what is stream selection

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [7]:
data = pd.read_csv('stream_selection_data.csv')

In [8]:
df = pd.DataFrame(data)

In [9]:
df

,Student_ID,Major_Stream,Minor_Specialization,Mid_Instruction,State_Region
0,ST_0000001,Science,PCM (Physics-Chemistry-Maths),English,Haryana
1,ST_0000002,Science,PCB (Physics-Chemistry-Biology),English,Telangana
2,ST_0000003,Science,PCMB (General Science),Hindi,Uttar Pradesh
3,ST_0000004,Arts,History-PolScience-Sociology,Hindi,Rajasthan
4,ST_0000005,Arts,Psychology-Economics-Literature,English,Delhi
5,ST_0000006,Arts,Geography-History-PublicAdmin,Regional,Gujarat
6,ST_0000007,Commerce,Accountancy-BusinessStudies-Maths,English,Karnataka
7,ST_0000008,Commerce,Accountancy-Economics-Informatics,English,Maharashtra
8,ST_0000009,Vocational,ITI Computer Operator & Programming,English,Tamil Nadu
9,ST_0000010,Vocational,Diploma in Mechanical Engineering,Regional,Punjab

In [15]:
df.head()

,Student_ID,Major_Stream,Minor_Specialization,Mid_Instruction,State_Region
0,ST_0000001,Science,PCM (Physics-Chemistry-Maths),English,Haryana
1,ST_0000002,Science,PCB (Physics-Chemistry-Biology),English,Telangana
2,ST_0000003,Science,PCMB (General Science),Hindi,Uttar Pradesh
3,ST_0000004,Arts,History-PolScience-Sociology,Hindi,Rajasthan
4,ST_0000005,Arts,Psychology-Economics-Literature,English,Delhi

In [16]:
df.tail()

,Student_ID,Major_Stream,Minor_Specialization,Mid_Instruction,State_Region
5,ST_0000006,Arts,Geography-History-PublicAdmin,Regional,Gujarat
6,ST_0000007,Commerce,Accountancy-BusinessStudies-Maths,English,Karnataka
7,ST_0000008,Commerce,Accountancy-Economics-Informatics,English,Maharashtra
8,ST_0000009,Vocational,ITI Computer Operator & Programming,English,Tamil Nadu
9,ST_0000010,Vocational,Diploma in Mechanical Engineering,Regional,Punjab

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student_ID            10 non-null     object
 1   Major_Stream          10 non-null     object
 2   Minor_Specialization  10 non-null     object
 3   Mid_Instruction       10 non-null     object
 4   State_Region          10 non-null     object
dtypes: object(5)
memory usage: 532.0+ bytes

In [20]:
df["Student_ID"]

0    ST_0000001
1    ST_0000002
2    ST_0000003
3    ST_0000004
4    ST_0000005
5    ST_0000006
6    ST_0000007
7    ST_0000008
8    ST_0000009
9    ST_0000010
Name: Student_ID, dtype: object